### ISSUE TITLE
繪製標題跟主題圖片

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/voc4fun-client#1]
請繪製Voc4Fun的icon
512px
從findicons或其他icon圖庫找尋免費圖片
http://findicons.com/
或是自己畫

再用icon slayer畫成像icon的樣子 (只有圖片也可以)
http://www.gieson.com/Library/projects/utilities/icon_slayer/#.VlMgT3YrJQI

建議製作一份SVG的原始檔案
然後轉換成512px \* 512px 的PNG檔案 （只能用PNG

---

主題圖片必須是 1024 x 500 (準確尺寸)
可以用這個來做
http://www.norio.be/android-feature-graphic-generator/

**Comment by abook013** [comment]
![voc4fun icon](https://cloud.githubusercontent.com/assets/15921168/11390736/d8940f90-9387-11e5-9e22-7a5cd9004de1.png)
![voc4fun](https://cloud.githubusercontent.com/assets/15921168/11390789/329feda6-9388-11e5-85bb-b1964110425f.png)
