### ISSUE TITLE
撰寫指標的說明

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/voc4fun-client#7]
請列出

[指標名稱]：[50個字以內的說明]

**Comment by abook013** [comment]
指標說明

單字
設定每天要學習的單字數量
建議剛開始學習，每日以10~ 20個單字為目標

筆記
設定每天要撰寫的筆記數量
針對不同單字，寫下你對不同單字的筆記與想法
字數及內容不拘，可隨意發揮

測驗答對題數
設定每天要答對的題目數量
APP將根據你所學的單字，產生測驗題目
題目為三選一的選擇題
